#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Arthur Silva'
        hostname: Ubuntu
        username: arthursilva
        password: '$6$1KI8YaC79Ywzvlkx$HkxCIzs7NuN/XGX.rowpxHjUlN9HrkijtVeZW./Yblrh82A1PG1q7Hn/QwrVtRaImGxwuJTofu32U93GEIwg80'
    locale: pt_BR.UTF-8
    keyboard:
        layout: br
    timezone: "America/Maceio"   
    packages:
        - gcc
        - g++
        - gdb
        - default-jdk
        - git
        - nodejs
        - npm
        - geany
        - geany-plugins
        - gimp
        - vlc
        - guvcview
        - virtualbox
        - virtualbox-guest-additions-iso
        - gparted
        - cpu-x
        - soundconverter
        - gufw
        - handbrake
        - gnome-boxes
        - gnome-calendar
        - ubuntu-restricted-extras
        - xournalpp
        - flatpak
    snaps:
    
        - name: brave
          channel: stable

        - name: motrix
          channel: stable

        - name: bitwarden
          channel: stable

        - name: image-optimizer
          channel: stable
        
        - name: firefox
          channel: stable

        - name: pycharm-community
          channel: stable
          classic: true

        - name: intellij-idea-community
          channel: stable
          classic: true

        - name: code
          channel: stable
          classic: true
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    late-commands:
        - curtin in-target -- apt update && apt upgrade -y

        # Adiciona reposit처rio e instala Google Chrome
        - curtin in-target -- wget -qO- https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
        - curtin in-target -- echo "deb [signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
        - curtin in-target -- apt update
        - curtin in-target -- apt install -y google-chrome-stable

        # Adiciona reposit처rio e instala AnyDesk
        - curtin in-target -- wget -qO- https://keys.anydesk.com/repos/DEB-GPG-KEY | gpg --dearmor -o /usr/share/keyrings/anydesk-keyring.gpg
        - curtin in-target -- echo "deb [signed-by=/usr/share/keyrings/anydesk-keyring.gpg] http://deb.anydesk.com/ all main" | tee /etc/apt/sources.list.d/anydesk.list
        - curtin in-target -- apt update
        - curtin in-target -- apt install -y anydesk

        # Adiciona reposit처rio e instala Flatpaks
        - curtin in-target -- flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        - curtin in-target -- flatpak install --assumeyes flathub net.ankiweb.Anki
        - curtin in-target -- flatpak install --assumeyes flathub com.github.finefindus.eyedropper
        - curtin in-target -- flatpak install --assumeyes flathub io.github.shiftey.Desktop
        - curtin in-target -- flatpak install --assumeyes flathub org.eclipse.Java
        - curtin in-target -- flatpak install --assumeyes flathub org.gaphor.Gaphor
        - curtin in-target -- flatpak install flathub io.dbeaver.DBeaverCommunity

        # Define o tema escuro padr찾o
        - curtin in-target -- gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-dark'
        - curtin in-target -- gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
        - curtin in-target -- gsettings set org.gnome.desktop.interface icon-theme 'Yaru-dark'
    shutdown: reboot

